name: Generate Profile Cards

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Momimus
          BRANCH_NAME: main
          # themes: github_dark, github, nord_dark, solarized, etc
          THEME: github_dark
